import { useEffect, useState, type CSSProperties, type ReactNode } from "react";
import { Link } from "@tanstack/react-router";
import { externalLinks } from "../config/links";

const nav = [
  ["Experience", "experience"], ["POS", "pos"], ["Payments", "payments"],
  ["Operations", "operations"], ["Technology", "technology"],
] as const;

function ArrowIcon() { return <svg viewBox="0 0 20 20" aria-hidden="true"><path d="M4 10h11M11 6l4 4-4 4" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg>; }
function MenuIcon({ open }: { open: boolean }) { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={open ? "M6 6l12 12M18 6L6 18" : "M4 8h16M4 16h16"} fill="none" stroke="currentColor" strokeWidth="1.5"/></svg>; }
function ReplayIcon() { return <svg viewBox="0 0 20 20" aria-hidden="true"><path d="M15.5 7A6 6 0 1 0 16 12M15.5 7V3m0 4h-4" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg>; }

export function Button({ href, children, variant = "primary" }: { href: string; children: ReactNode; variant?: "primary" | "outline" | "green" }) {
  const className = `button button--${variant}`;
  if (href.startsWith("/")) return <Link className={className} to={href}>{children}<ArrowIcon /></Link>;
  return <a className={className} href={href}>{children}<ArrowIcon /></a>;
}
export function Badge({ children, dark = false }: { children: ReactNode; dark?: boolean }) { return <span className={`badge ${dark ? "badge--dark" : ""}`}>{children}</span>; }
export function StatusIndicator({ status, children }: { status: "available" | "occupied" | "pending" | "paid"; children: ReactNode }) { return <span className={`status status--${status}`}><i />{children}</span>; }
export function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
export function SectionHeader({ eyebrow, title, copy, dark = false }: { eyebrow: string; title: ReactNode; copy?: string; dark?: boolean }) { return <header className={`section-header ${dark ? "section-header--dark" : ""}`}><p>{eyebrow}</p><h2>{title}</h2>{copy && <div>{copy}</div>}</header>; }
export function TransactionRow({ label, value, quiet = false }: { label: string; value: string; quiet?: boolean }) { return <div className={`transaction-row ${quiet ? "transaction-row--quiet" : ""}`}><span>{label}</span><strong>{value}</strong></div>; }
export function TableStatus({ number, state, amount, shape = "round" }: { number: string; state: "available" | "occupied" | "pending" | "paid"; amount?: string; shape?: "round" | "square" | "long" }) { return <div className={`floor-table floor-table--${shape} floor-table--${state}`}><b>{number}</b><StatusIndicator status={state}>{state === "paid" ? "Paid" : state === "pending" ? "Payment pending" : state.charAt(0).toUpperCase() + state.slice(1)}</StatusIndicator>{amount && <small>{amount}</small>}</div>; }

export function Navbar() {
  const [solid, setSolid] = useState(false); const [open, setOpen] = useState(false);
  useEffect(() => { const onScroll = () => setSolid(window.scrollY > 24); onScroll(); addEventListener("scroll", onScroll, { passive: true }); return () => removeEventListener("scroll", onScroll); }, []);
  return <nav className={`navbar ${solid ? "navbar--solid" : ""}`}>
    <a className="brand" href="#top"><b>MARA HOUSE</b><span>Powered by TillFlow</span></a>
    <div className={`nav-links ${open ? "nav-links--open" : ""}`}>{nav.map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setOpen(false)}>{label}</a>)}</div>
    <div className="nav-actions"><Link to="/demo">View Demo</Link>{externalLinks.github && <a href={externalLinks.github}>GitHub</a>}<button aria-label={open ? "Close menu" : "Open menu"} onClick={() => setOpen(!open)}><MenuIcon open={open} /></button></div>
  </nav>;
}

export function POSPreview({ hero = false }: { hero?: boolean }) {
  return <div className={`pos-panel ${hero ? "pos-panel--hero" : ""}`}>
    <div className="panel-top"><div><span>MARA HOUSE</span><small>DINNER SERVICE · 21 SEPTEMBER</small></div><Badge>Live floor</Badge></div>
    <div className="pos-table-meta"><div><small>TABLE</small><strong>07</strong></div><div><small>GUESTS</small><strong>4</strong></div><div><small>SERVER</small><strong>AM</strong></div></div>
    <div className="pos-items"><TransactionRow label="2 × Grilled Sea Bass" value="4,600"/><TransactionRow label="1 × Pasta" value="1,650"/><TransactionRow label="2 × Sparkling Water" value="1,600" quiet /></div>
    <div className="pos-total"><span>TOTAL</span><strong>KES 7,850</strong></div>
    <div className="pos-payment"><StatusIndicator status="pending">PAYMENT PENDING</StatusIndicator><Link to="/demo">M-PESA</Link></div>
  </div>;
}

export function RestaurantHero() { return <section className="restaurant-hero" id="top"><div className="ambient-light"/><div className="hero-copy"><p className="eyebrow">MARA HOUSE · NAIROBI</p><h1>Every table.<br/>Every order.<br/><em>Every payment.</em></h1><p>TillFlow gives modern restaurants one place to manage service, payments and daily operations.</p><div className="button-row"><Button href="#pos">Explore TillFlow</Button><Button href="/demo" variant="outline">See the POS</Button></div></div><div className="hero-visual"><div className="restaurant-sign"><span>Contemporary African Dining</span><b>M</b><small>NAIROBI · EVENING SERVICE</small></div><POSPreview hero /></div><div className="hero-foot"><span>01</span><p>Hospitality, connected from the room to the receipt.</p><i /></div></section>; }

export function IntroFlow() { const steps = ["TABLE", "ORDER", "PAYMENT", "CONFIRMED", "SALES"]; return <section className="intro section" id="experience"><SectionHeader eyebrow="The service flow" title="Beautiful service needs a system behind it." copy="From the first order to the final payment, TillFlow keeps the restaurant floor connected to the operations behind it."/><div className="intro-flow">{steps.map((step, i) => <div key={step}><span>0{i+1}</span><strong>{step}</strong>{i < steps.length - 1 && <i><ArrowIcon/></i>}</div>)}</div></section>; }

export function RestaurantFloor() { return <section className="section floor-section"><div className="split-heading"><SectionHeader eyebrow="Floor management · Concept UI" title="See the room at a glance."/><p>Move through service with a clear view of every table, tab and payment state.</p></div><div className="floor-shell"><div className="floor-toolbar"><div><b>MARA HOUSE · MAIN ROOM</b><span>DINNER · 19:42</span></div><Badge>Sample data</Badge></div><div className="floor-plan"><div className="window-line">WINDOWS · CITY VIEW</div><div className="bar-edge"><b>BAR</b><span>12 SEATS</span></div><TableStatus number="01" state="available"/><TableStatus number="02" state="occupied" amount="KES 4,850" shape="square"/><TableStatus number="03" state="occupied" amount="KES 8,420" shape="long"/><TableStatus number="04" state="paid"/><TableStatus number="05" state="occupied" amount="KES 3,250" shape="square"/><TableStatus number="06" state="pending" amount="KES 6,850"/><TableStatus number="07" state="available" shape="long"/></div><div className="floor-legend"><StatusIndicator status="available">Available</StatusIndicator><StatusIndicator status="occupied">Occupied</StatusIndicator><StatusIndicator status="pending">Payment pending</StatusIndicator><StatusIndicator status="paid">Paid</StatusIndicator></div></div></section>; }

export function OrderPreview() { const groups = [{title:"STARTERS",items:["2 × Samosa","1 × Roasted Corn"]},{title:"MAINS",items:["2 × Grilled Fish","1 × Jollof Rice","1 × Seasonal Vegetables"]},{title:"DRINKS",items:["2 × Sparkling Water"]}]; return <section className="section order-section" id="pos"><SectionHeader eyebrow="Order management · Concept UI" title="From order to kitchen." copy="The details the room needs, in the order the kitchen expects."/><div className="order-layout"><div className="order-panel"><div className="panel-top"><div><span>TABLE 12</span><small>4 GUESTS · ORDER #1048</small></div><Badge>Illustrative</Badge></div>{groups.map(g => <div className="order-group" key={g.title}><b>{g.title}</b>{g.items.map(x => <span key={x}>{x}</span>)}</div>)}<div className="pos-total"><span>TOTAL</span><strong>KES 6,850</strong></div></div><div className="order-progress"><Badge>Sample status</Badge><h3>Service, without the guesswork.</h3><p>Each stage remains visible from the first ticket to the final plate.</p><div className="progress-track">{["Received","Preparing","Ready","Served"].map((x,i) => <div className={i === 1 ? "is-active" : i < 1 ? "is-done" : ""} key={x}><i>{i < 1 ? "✓" : i+1}</i><span>{x}</span></div>)}</div></div></div></section>; }

export function PaymentPreview() { const [confirmed, setConfirmed] = useState(false); const replay = () => { setConfirmed(false); window.setTimeout(() => setConfirmed(true), 700); }; useEffect(() => { const t = window.setTimeout(() => setConfirmed(true), 1800); return () => clearTimeout(t); }, []); return <div className={`payment-panel ${confirmed ? "payment-panel--confirmed" : ""}`}><div className="payment-head"><div><small>ORDER #1042</small><strong>KES 4,850</strong></div><Badge>Illustrative</Badge></div><div className="payment-method"><span>M-PESA</span><i>Mobile payment</i></div><div className="payment-request"><small>{confirmed ? "CALLBACK RECEIVED" : "PAYMENT REQUEST SENT"}</small><strong>+254 ••• ••• 421</strong></div><div className="confirmation-state"><div className="confirmation-icon">{confirmed ? "✓" : <i/>}</div><div><strong>{confirmed ? "PAYMENT CONFIRMED" : "WAITING FOR CONFIRMATION"}</strong><span>{confirmed ? "Order #1042 is ready to close" : "Listening for M-Pesa callback"}</span></div></div><button className="replay" onClick={replay} aria-label="Replay payment confirmation"><ReplayIcon/> Replay</button></div>; }

export function MpesaFlow() { return <div className="mpesa-flow"><div><small>ORDER</small><strong>KES 4,850</strong></div><i><ArrowIcon/></i><div><small>PAYMENT RAIL</small><strong>M-PESA</strong></div><i><ArrowIcon/></i><div><small>RESPONSE</small><strong>CALLBACK</strong></div><i><ArrowIcon/></i><div className="flow-confirmed"><small>STATUS</small><strong>✓ CONFIRMED</strong></div></div>; }
export function PaymentsSection() { return <section className="payments-band section" id="payments"><div className="payments-layout"><div><SectionHeader eyebrow="Connected payments" title="Payment should be the easy part." copy="TillFlow connects the restaurant’s transaction flow to payment confirmation, including M-Pesa."/><div className="payment-note"><span>01</span><p>The order and payment status stay connected, so the floor knows what happened.</p></div></div><PaymentPreview/></div><div className="mpesa-block"><SectionHeader eyebrow="M-Pesa flow" title="Made for the way customers pay." copy="Connect restaurant transactions to M-Pesa payment flows and keep payment status connected to the order."/><MpesaFlow/><p className="scope-note">Scope shown: STK push request · Callback · Status confirmation</p><p className="scope-note"><Link to="/demo">Try a real payment flow →</Link></p></div></section>; }

export function OperationsDashboard() { return <section className="section operations" id="operations"><SectionHeader eyebrow="Daily operations" title="Know how the day is going." copy="A quiet, useful view of service as it unfolds."/><div className="dashboard"><div className="dashboard-top"><div><b>TODAY · 21 SEPTEMBER</b><span>DINNER SERVICE</span></div><Badge>Sample data</Badge></div><div className="metrics"><Metric label="Sales" value="KES 184,250"/><Metric label="Orders" value="47"/><Metric label="Tables" value="32"/><Metric label="Payments" value="45"/></div><div className="dashboard-lower"><div className="sales-chart"><div><b>HOURLY SALES</b><span>KES</span></div><svg viewBox="0 0 600 180" role="img" aria-label="Illustrative hourly sales line"><path className="grid-line" d="M0 30H600M0 90H600M0 150H600"/><path className="chart-line" d="M0 151 C70 145 88 122 140 128 S220 94 270 101 S348 60 390 75 S470 30 520 45 S575 28 600 17"/><path className="chart-fill" d="M0 151 C70 145 88 122 140 128 S220 94 270 101 S348 60 390 75 S470 30 520 45 S575 28 600 17V180H0Z"/></svg><div className="chart-labels"><span>17:00</span><span>19:00</span><span>21:00</span><span>23:00</span></div></div><div className="top-selling"><b>TOP SELLING</b><TransactionRow label="Grilled Sea Bass" value="18 orders"/><TransactionRow label="Jollof Rice" value="14 orders"/><TransactionRow label="Mara House Salad" value="11 orders"/></div></div></div></section>; }

export function MultiTenantVisual() { return <section className="section tenant-section"><SectionHeader eyebrow="Multi-tenant design · Conceptual view" title="One system. Multiple businesses." copy="A clear separation of businesses and locations, connected through one operating system."/><div className="tenant-map"><div className="tenant-origin"><span>MARA HOUSE</span><small>Nairobi</small></div><div className="tenant-line"/><div className="tillflow-core"><span>TF</span><b>TILLFLOW</b><small>SHARED PLATFORM</small></div><div className="tenant-line"/><div className="tenant-list"><div><span>MH</span><p><b>Mara House</b><small>Karen</small></p></div><div><span>MH</span><p><b>Mara House</b><small>Westlands</small></p></div><div><span>DR</span><p><b>Demo Restaurant</b><small>Nairobi</small></p></div></div></div><Badge>Illustrative architecture</Badge></section>; }

const architectureNodes = [{x:20,y:126,w:110,label:"MARA HOUSE",sub:"Restaurant"},{x:170,y:126,w:100,label:"TILLFLOW",sub:"Platform"},{x:315,y:126,w:110,label:"API GATEWAY",sub:"Ingress"},{x:470,y:126,w:80,label:"ALB",sub:"Routing"},{x:600,y:32,w:115,label:"POS",sub:"Service"},{x:600,y:126,w:115,label:"PAYMENTS",sub:"Service"},{x:600,y:220,w:115,label:"COMMISSION",sub:"Service"},{x:770,y:58,w:90,label:"RDS",sub:"Data"},{x:770,y:194,w:90,label:"VALKEY",sub:"Cache"},{x:915,y:95,w:85,label:"SQS",sub:"Queue"},{x:1045,y:95,w:85,label:"DLQ",sub:"Fallback"},{x:770,y:300,w:130,label:"M-PESA",sub:"Daraja"}];
export function ArchitectureDiagram() { return <div className="architecture-scroll"><div className="architecture"><svg viewBox="0 0 1160 390" aria-hidden="true"><g className="connections"><path d="M130 156H170M270 156H315M425 156H470M550 156H575V62H600M550 156H600M550 156H575V250H600M715 62H745V88H770M715 156H745V88H770M715 156H745V224H770M715 250H745V224H770M860 88H885V125H915M860 224H885V125H915M1000 125H1045M657 186V330H770"/></g></svg>{architectureNodes.map(n => <div key={n.label} className={`arch-node ${n.label === "TILLFLOW" ? "arch-node--core" : ""} ${n.label === "M-PESA" ? "arch-node--external" : ""}`} style={{left:n.x,top:n.y,width:n.w}}><b>{n.label}</b><small>{n.sub}</small></div>)}</div></div>; }

export function SystemIntro() { return <section className="system-intro" id="technology"><div className="system-mark"><span>TF</span></div><SectionHeader dark eyebrow="The TillFlow system" title={<>Behind every simple transaction is a system <em>built to keep up.</em></>} copy="A considered service architecture connects the restaurant floor to payments, data and operational workflows."/><div className="system-tech-line">{["AWS","ECS Fargate","API Gateway","ALB","RDS","Valkey","SQS","Terraform","GitHub Actions"].map(x=><span key={x}>{x}</span>)}</div></section>; }
export function ArchitectureSection() { return <section className="technical-section"><div className="technical-inner"><div className="split-heading split-heading--dark"><SectionHeader dark eyebrow="System architecture" title="Clear paths. Defined responsibilities."/><p>Illustrative architecture showing how requests, services, data and payment events move through TillFlow.</p></div><ArchitectureDiagram/><div className="architecture-legend"><span><i/>Internal flow</span><span><i/>External payment connection</span><Badge dark>Conceptual diagram</Badge></div></div></section>; }

const reliability = [["01","Health & readiness","Health checks and readiness gates keep traffic directed to services prepared to receive it."],["02","Payment integrity","Idempotent processing helps repeated requests resolve to one intended transaction outcome."],["03","Queue resilience","Queues separate workloads; dead-letter handling makes failed events visible for recovery."],["04","Operational signals","Observability, service objectives and error budgets give teams a shared view of reliability."]];
export function ReliabilitySection() { return <section className="technical-section reliability"><div className="technical-inner"><SectionHeader dark eyebrow="Reliability" title={<>Simple for the restaurant.<br/><em>Thoughtful underneath.</em></>}/><div className="reliability-list">{reliability.map(([n,t,c])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div></div></section>; }
export function EngineeringStack() { const stages=[{n:"01",t:"DEFINE",x:"Terraform",d:"Infrastructure as Code"},{n:"02",t:"PACKAGE",x:"Docker",d:"Consistent workloads"},{n:"03",t:"DEPLOY",x:"ECS Fargate",d:"Managed containers"},{n:"04",t:"VERIFY",x:"GitHub Actions",d:"CI/CD workflows"},{n:"05",t:"REVIEW",x:"CODEOWNERS",d:"Clear responsibility"}]; return <section className="technical-section engineering"><div className="technical-inner"><SectionHeader dark eyebrow="Engineering foundations" title="Built with the same attention to detail." copy="Delivery and infrastructure practices presented as one coherent operating discipline."/><div className="pipeline">{stages.map((s,i)=><div key={s.n}><span>{s.n} · {s.t}</span><b>{s.x}</b><small>{s.d}</small>{i<stages.length-1&&<i><ArrowIcon/></i>}</div>)}</div></div></section>; }

export function TransactionJourney() { const steps=["Customer orders","Order created","Payment initiated","M-Pesa callback received","Payment confirmed","Transaction completed"]; return <section className="technical-section journey"><div className="technical-inner"><SectionHeader dark eyebrow="Transaction journey" title="From table to confirmation."/><div className="journey-track">{steps.map((s,i)=><div style={{"--delay":`${i*120}ms`} as CSSProperties} key={s}><span>{String(i+1).padStart(2,"0")}</span><i/><b>{s}</b></div>)}</div></div></section>; }

export function DemoCTA() { return <section className="cta-section"><SectionHeader eyebrow="Live product" title="Step behind the counter." copy="Explore how TillFlow brings orders, payments and operations together."/><Button href="/demo">Try the Demo</Button></section>; }
export function GitHubCTA() { if (!externalLinks.github && !externalLinks.documentation) return null; return <section className="technical-section github-cta"><div className="technical-inner"><SectionHeader dark eyebrow="Under the hood" title="Want to see how it works underneath?" copy="Explore the architecture, infrastructure and delivery workflows behind TillFlow."/><div className="button-row">{externalLinks.github&&<Button href={externalLinks.github} variant="green">View GitHub</Button>}{externalLinks.documentation&&<Button href={externalLinks.documentation} variant="outline">View Documentation</Button>}</div></div></section>; }
export function FinalSection() { return <section className="final-section"><p>MARA HOUSE · NAIROBI</p><h2>A better service starts<br/><em>behind the scenes.</em></h2><div><span>MARA HOUSE</span><i>Powered by TillFlow</i></div><Button href="#pos">Explore TillFlow</Button></section>; }
export function Footer() { return <footer><div className="footer-brand"><b>MARA HOUSE</b><span>Powered by TillFlow</span></div><div className="footer-links">{nav.slice(1).map(([label,id])=><a key={id} href={`#${id}`}>{label}</a>)}{externalLinks.github&&<a href={externalLinks.github}>GitHub</a>}</div><span>Group 10</span></footer>; }

export default function TillflowSite() { return <><Navbar/><main><RestaurantHero/><IntroFlow/><RestaurantFloor/><OrderPreview/><PaymentsSection/><OperationsDashboard/><MultiTenantVisual/><SystemIntro/><ArchitectureSection/><ReliabilitySection/><EngineeringStack/><TransactionJourney/><DemoCTA/><GitHubCTA/><FinalSection/></main><Footer/></>; }
